main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")
if main_menu == "Credits":
    credits = input("Main Developers: Kai and Owen Productions  Teacher: Mr. Whalen Side  Contributors: Team Google  People We Used to Copy: Gabe and Yizhak Productions  Choices: Back ")
    if credits == "Back":
        main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")
    else:
        print("That's not a choice kid... ")
        main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")
if main_menu == "Tutorial":
    tutorial = input("The game is rather simple; you can think of it as a more complex form of rock, paper, scissors. There are five attacks: Jab, Straight, Left Hook, Right Hook, and Right Uppercut. Each can be countered with their respective block(e.g. Jab will be blocked by the move Block Jab). This game is also more of a turn-based game with you and the enemy taking turns attacking and defending until one of you gets defeated. Attacking will use up stamina depending on which attacks you use. Stamina can be replenished by resting which will cause you to use up your current turn which can make you either unable to attack or unable to defend. That's really all there is to this game, so go on and have fun!  Choices: Back ")
    if tutorial == "Back":
        main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")
    else:
        print("That's not a choice kid... ")
        main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")
if main_menu == "Play":
    print("Here we go! ")
else:
    print("That's not a choice kid... ")
    main_menu = input("Kai and Owen Productions Presents: Punch-A-Looza! This all new boxing styled fighting game will most surely bring joy to all of its players! The game revolves around the player who has always had a dream of becoming a boxing star ever since their childhood. Seeing various boxing stars on TV such as Mike Tyson and Muhammed Ali has set your heart ablaze with dreams of becoming like them and fighting on the world stage. Unable to wait any longer, you decide to join a boxing gym and make a name for yourself. You will encounter many enemies but you are confident that you will be able to beat every single one of them to the ground if they try to stop you from achieving your dream. The choice is yours: Will you beat down everyone in your path and become the boxing champion of the world? Or, will you get beaten by your next opponent and end up never achieving your dream? Please give any feedback and report any bugs to the company! It really helps us a lot!  Choices: Play/Credits/Tutorial ")